### ISSUE TITLE
Draft includes wrong Github links

### ISSUE THREAD

**Issue by ssstolk** [w3c/dx-connegp#36]
The working draft at https://www.w3.org/TR/2019/WD-dx-prof-conneg-20191126/ includes links for participation to GitHub that still point to an old respository for content and issues. Indeed, this was the reason for inclusion of my raised issues in the dxwg repository rather than here. (These issues have since been moved to this repository.)

Please change the GitHub links in this section to point to w3c/dx-connegp:
```
Participate:
GitHub w3c/dxwg
File a bug  
```

**Comment by larsgsvensson** [comment]
Yes, we're aware of that. The cause of the problem is that we re-structured the github repo after publishing the last WD and we cannot make changes to an already published document - we can only publish a new WD where this link is fixed (which would also fix the broken link to the current ED)...
The most up-to-date version is the [Editors' draft](https://w3c.github.io/dx-connegp/connegp/) that links to the correct repo and issues locations.
And we're happy that you've taken time to review our documents. Thank you!

**Comment by rob-metalinkage** [comment]
need to update the canonical location
